version: '3'

services:
  watchdog:
    build: 
      dockerfile: Dockerfile
      context: ../
    image: feather_watchdog
    environment:
      INFLUXDB_URL: http://influxdb:8086
    links:
      - influxdb
    command: "python get_readings.py"
