version: '3'
services:
  telegraf:
    image: telegraf:1.7.2
    volumes:
      - ./etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    environment:
      INFLUXDB_URL: $INFLUX_URL
      UNIT_ID: "$TXID"
    ports:
      - "8092:8092/udp"
      - "8094:8094"
      - "8125:8125/udp"
  watchdog:
    build: 
      dockerfile: Dockerfile
      context: ../
    image: feather_watchdog
    environment:
      INFLUXDB_URL: $INFLUX_URL
      UNIT_ID: "$TXID"
    command: "python get_onboard_readings.py"
