version: '3'

services:
  watchdog:
    build: 
      dockerfile: Dockerfile
      context: ../
    image: feather_watchdog
    environment:
      INFLUXDB_URL: http://192.168.1.110:8086
    command: "python get_onboard_readings.py"
